CREATE DATABASE cms;

USE cms;

CREATE TABLE user(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	nic VARCHAR(15) NOT NULL UNIQUE,
	department VARCHAR(100),
	email VARCHAR(100),
	password VARCHAR(255) NOT NULL,
	role ENUM('EMPLOYEE', 'ADMIN') NOT NULL
);

CREATE TABLE complain(
	id INT AUTO_INCREMENT PRIMARY KEY,
  	user_id INT NOT NULL,
  	title VARCHAR(255) NOT NULL,
  	description TEXT,
 	status ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED') DEFAULT 'PENDING',
  	remarks TEXT,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE

);